- name: "Include alert manager variables"
  include_vars: 'alertmanager.yml'

- name: "Creating alert manager directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    mode: 0750
  with_items:
    - "{{ library_directory_path }}"
    - "{{ prometheus_config_dir }}"
    - "{{ alert_manager_data_dirdirectory_path }}"
    - "{{ alert_manager_config_dirdirectory_path }}"
    - "{{ alert_manager_templates_dirdirectory_path }}"

- name: "Download and extract Prometheus alertmanager tarball"
  unarchive:
    src: "{{ prometheus_alert_manager_tarball_url }}"
    dest: "{{ installation_directory_path }}"
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    copy: no
    creates: "{{ installation_directory_path }}/{{ prometheus_alert_manager_archive }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Copy alert manager config"
  template:
    src: alertmanager.yml.j2
    dest: "{{ alert_manager_config_dirdirectory_path }}/alertmanager.yml"
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    validate: "{{ installation_directory_path }}/{{ prometheus_alert_manager_archive }}/amtool check-config %s --alertmanager.url={{ _alert_manager_validate_url }}"
  notify:
    restart alertmanager

- name: "Install Prometheus alert manager systemd service"
  template:
    src: alert_manager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify:
    - reload daemon
    - restart alertmanager
