- name: "Include node exporter variables"
  include_vars: 'nodeexporter.yml'

- name: "Download and extract Prometheus node exporter tarball"
  unarchive:
    src: "{{ prometheus_node_exporter_tarball_url }}"
    dest: "{{ installation_directory_path }}"
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    copy: no
    creates: "{{ installation_directory_path }}/{{ prometheus_node_exporter_archive }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Install Prometheus node exporter systemd service"
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/nodeexporter.service
  notify:
    - reload daemon
    - restart nodeexporter
