- name: "Include pushgateway variables"
  include_vars: 'pushgateway.yml'

- name: "Download and extract Prometheus push gateway tarball"
  unarchive:
    src: "{{ prometheus_push_gateway_tarball_url }}"
    dest: "{{ installation_directory_path }}"
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    copy: no
    creates: "{{ installation_directory_path }}/{{ prometheus_push_gateway_archive }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Install Prometheus push gateway systemd service"
  template:
    src: push_gateway.service.j2
    dest: /etc/systemd/system/pushgateway.service
  notify:
    - reload daemon
    - restart pushgateway
