- name: "Include blackbox exporter variables"
  include_vars: 'blackboxexporter.yml'

- name: "Creating blackbox exporter directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    mode: 0750
  with_items:
    - "{{ server_configuration_directory_path }}"
    - "{{ blackbox_exporter_config_directoy_path }}"

- name: "Download and extract Prometheus blackbox_exporter tarball"
  unarchive:
    src: "{{ prometheus_blackbox_exporter_tarball_url }}"
    dest: "{{ installation_directory_path }}"
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    copy: no
    creates: "{{ installation_directory_path }}/{{ prometheus_blackbox_exporter_archive }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Copy blackbox exporter config"
  template:
    src: blackbox.yml.j2
    dest: "{{ blackbox_exporter_config_directoy_path }}/blackbox.yml"
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
  notify:
    - reload blackboxexporter

- name: "Apply elevated privileges to blackbox_exporter for ICMP probe"
  capabilities:
    path: "{{ installation_directory_path }}/{{ prometheus_blackbox_exporter_archive }}/blackbox_exporter"
    capability: cap_net_raw+ep
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - reload blackboxexporter

- name: "Install Prometheus blackbox exporter systemd service"
  template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackboxexporter.service
  notify:
    - reload daemon
    - restart blackboxexporter
