- name: "Include prometheus variables"
  include_vars: 'prometheus.yml'

- name: "Creating Prometheus directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    mode: 0750
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ data_directory_path }}"
    - "{{ library_directory_path }}"
    - "{{ rules_directory_path }}"

- name: "Download and extract Prometheus tarball"
  unarchive:
    src: "{{ prometheus_tarball_url }}"
    dest: "{{ installation_directory_path }}"
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    copy: no
    creates: "{{ installation_directory_path }}/{{ prometheus_archive }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: "Copy Prometheus config"
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    validate: "{{ installation_directory_path }}/{{ prometheus_archive }}/promtool check config %s"
  notify:
    restart prometheus

- name: "Making Prometheus rules file {{ item.name }}"
  copy:
    content: "{{ { 'groups': [item] } | to_json | regex_replace('\\[\\[', '{{') | regex_replace('\\]\\]', '}}') | from_json | to_nice_yaml }}"
    dest: "{{ rules_directory_path }}/{{ item.name }}.rules.yml"
    owner: "{{ owner_name }}"
    group: "{{ group_name }}"
    validate: "{{ installation_directory_path }}/{{ prometheus_archive }}/promtool check rules %s"
  with_items: "{{ prometheus_rules }}"
  when: prometheus_rules | length > 0
  notify:
    restart prometheus

- name: "Install Prometheus systemd service"
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - reload daemon
    - restart prometheus
