---
# tasks file for ansible-prometheus
- name: "Create Prometheus group."
  group:
    name: "{{ group_name }}"
    state: present

- name: "Create Prometheus user"
  user:
    name: "{{ owner_name }}"
    group: "{{ group_name }}"
    createhome: no
    shell: /sbin/nologin
    state: present

- name: "Create {{ installation_directory_path }}"
  file:
    path: "{{ installation_directory_path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: "Install Prometheus."
  import_tasks: install-prometheus.yml
  when: server_install_status

- name: "Install Prometheus node exporter"
  import_tasks: install-node-exporter.yml
  when: node_exporter_install_status

- name: "Install Prometheus alert manager."
  import_tasks: install-alert-manager.yml
  when: alert_manager_install_status

- name: "Install Pushgateway."
  import_tasks: install-push-gateway.yml
  when: push_gateway_install_status

- name: "Install Prometheus SNMP exporter."
  import_tasks: install-snmp-exporter.yml
  when: snmp_exporter_install_status

- name: "Install Prometheus Blackbox exporter."
  import_tasks: install-blackbox-exporter.yml
  when: blackbox_exporter_install_status
